# Generated by Django 4.2.16 on 2026-06-06 05:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('check_in_date', models.DateField(verbose_name='Дата заселения')),
                ('expected_check_out_date', models.DateField(verbose_name='Планируемая дата выселения')),
                ('actual_check_out_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата выселения')),
                ('rate_type', models.CharField(choices=[('daily', 'Посуточно'), ('weekly', 'Понедельно'), ('monthly', 'Помесячно')], default='monthly', max_length=20, verbose_name='Тип тарифа')),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма тарифа (тенге)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Депозит (тенге)')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('checked_out', 'Выселен'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='active', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('direct', 'Напрямую'), ('krisha', 'Krisha.kz'), ('olx', 'OLX.kz'), ('booking', 'Booking.com'), ('instagram', 'Instagram'), ('referral', 'Рекомендация'), ('other', 'Другое')], default='direct', max_length=20, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stays', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='guests.guest', verbose_name='Гость')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='properties.unit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Проживание',
                'verbose_name_plural': 'Проживания',
                'ordering': ['-check_in_date'],
            },
        ),
    ]
