# Generated by Django 4.2.16 on 2026-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='mpis_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает регистрации'), ('submitted', 'Отправлено'), ('confirmed', 'Подтверждено')], default='not_required', help_text='Статус регистрации иностранного гостя в системе MPIS/eQonaq', max_length=20, verbose_name='Статус MPIS'),
        ),
    ]
