# Generated by Django 4.2.16 on 2026-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_mpis_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('unit',), name='unique_active_stay_per_unit'),
        ),
    ]
