# Generated by Django 4.2.16 on 2026-07-09 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stays", "0007_mpis_verbose_rename"),
    ]

    operations = [
        migrations.CreateModel(
            name="StayDateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("check_in_date", "Дата заселения"),
                            ("expected_check_out_date", "Планируемая дата выселения"),
                        ],
                        max_length=30,
                        verbose_name="Поле",
                    ),
                ),
                ("old_value", models.DateField(verbose_name="Было")),
                ("new_value", models.DateField(verbose_name="Стало")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина/комментарий"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stay_date_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_changes",
                        to="stays.stay",
                        verbose_name="Проживание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение даты проживания",
                "verbose_name_plural": "Изменения дат проживания",
                "ordering": ["-changed_at"],
            },
        ),
    ]
