# Generated by Django 4.2.16 on 2026-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0008_staydatechange"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="manual_total_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Если задано — используется вместо автоматического расчёта по тарифу.",
                max_digits=10,
                null=True,
                verbose_name="Сумма к оплате (ручная корректировка)",
            ),
        ),
    ]
