# Generated by Django 4.2.16 on 2026-06-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Объект размещения',
                'verbose_name_plural': 'Объекты размещения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('room_type', models.CharField(choices=[('dorm', 'Дормитори'), ('private', 'Приватная')], default='dorm', max_length=20, verbose_name='Тип')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Этаж')),
                ('max_capacity', models.PositiveSmallIntegerField(default=4, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('unit_type', models.CharField(choices=[('bed', 'Койко-место'), ('private_room', 'Отдельная комната'), ('apartment', 'Апартамент'), ('studio', 'Студия'), ('family_room', 'Семейный номер')], default='bed', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('available', 'Свободно'), ('occupied', 'Занято'), ('reserved', 'Забронировано'), ('dirty', 'Требует уборки'), ('maintenance', 'Техобслуживание'), ('out_of_order', 'Выведено из эксплуатации')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Юнит (место размещения)',
                'verbose_name_plural': 'Юниты (места размещения)',
                'ordering': ['room', 'sort_order', 'name'],
            },
        ),
    ]
