# Generated by Django 4.2.16 on 2026-06-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('source', models.CharField(choices=[('krisha', 'Krisha.kz'), ('olx', 'OLX.kz'), ('instagram', 'Instagram'), ('referral', 'Рекомендация'), ('direct', 'Напрямую'), ('other', 'Другое')], default='direct', max_length=20, verbose_name='Источник')),
                ('interested_unit_type', models.CharField(blank=True, max_length=50, verbose_name='Интересует тип')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет от')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет до')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('viewing_scheduled', 'Показ назначен'), ('viewed', 'Показ проведён'), ('negotiating', 'Обсуждение'), ('won', 'Заселился'), ('lost', 'Отказался')], default='new', max_length=30, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата конверсии')),
                ('converted_to_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='guests.guest', verbose_name='Конвертирован в гостя')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('conducted_at', models.DateTimeField(blank=True, null=True, verbose_name='Проведено в')),
                ('outcome', models.CharField(choices=[('pending', 'Ожидается'), ('no_show', 'Не явился'), ('interested', 'Заинтересован'), ('not_interested', 'Не заинтересован')], default='pending', max_length=20, verbose_name='Результат')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='leads.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Показ',
                'verbose_name_plural': 'Показы',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
