# Generated by Django 4.2.16 on 2026-06-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('_iin_encrypted', models.CharField(blank=True, db_column='iin_encrypted', max_length=500, verbose_name='ИИН (зашифрован)')),
                ('iin_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ИИН хэш')),
                ('document_type', models.CharField(choices=[('id_card', 'Удостоверение личности РК'), ('passport_kz', 'Паспорт РК'), ('passport_foreign', 'Иностранный паспорт'), ('residence_permit', 'ВНЖ'), ('other', 'Другое')], default='id_card', max_length=20, verbose_name='Тип документа')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Номер документа')),
                ('document_photo', models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Фото документа')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
