# Generated by Django 4.2.16 on 2026-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_foreigner',
            field=models.BooleanField(default=False, help_text='Требуется регистрация в MPIS/eQonaq', verbose_name='Иностранец'),
        ),
        migrations.AddField(
            model_name='guest',
            name='nationality',
            field=models.CharField(blank=True, help_text='Страна гражданства, напр. "Казахстан", "Россия", "Германия"', max_length=100, verbose_name='Гражданство'),
        ),
    ]
