# Generated by Django 4.2.16 on 2026-06-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('_iin_encrypted', models.CharField(blank=True, db_column='iin_encrypted', max_length=500)),
                ('iin_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ИИН хэш')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Телефон')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('reason', models.CharField(choices=[('debt', 'Долг / не заплатил'), ('theft', 'Кража'), ('vandalism', 'Вандализм'), ('fraud', 'Мошенничество'), ('behavior', 'Нарушение порядка'), ('other', 'Другое')], max_length=20, verbose_name='Причина')),
                ('description', models.TextField(verbose_name='Описание инцидента')),
                ('evidence_url', models.URLField(blank=True, verbose_name='Ссылка на доказательство')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_reports', to='organizations.organization', verbose_name='Добавлено организацией')),
            ],
            options={
                'verbose_name': 'Запись в чёрном списке',
                'verbose_name_plural': 'Чёрный список',
                'ordering': ['-created_at'],
            },
        ),
    ]
