# Generated by Django 4.2.16 on 2026-06-06 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stays', '0001_initial'),
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (тенге)')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('kaspi', 'Kaspi Transfer'), ('bank_transfer', 'Банковский перевод'), ('card', 'Карта')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('period_from', models.DateField(blank=True, null=True, verbose_name='Период с')),
                ('period_to', models.DateField(blank=True, null=True, verbose_name='Период по')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stays.stay', verbose_name='Проживание')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.CharField(choices=[('utility', 'Коммунальные услуги'), ('supply', 'Хозтовары / расходники'), ('maintenance', 'Ремонт и обслуживание'), ('salary', 'Зарплата'), ('advertising', 'Реклама'), ('tax', 'Налоги'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (тенге)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
    ]
