# Generated by Django 4.2.16 on 2026-07-08 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_deposit_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "org_name",
                    models.CharField(max_length=255, verbose_name="Название объекта"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "booking_mode",
                    models.CharField(
                        choices=[
                            ("hostel", "Хостел / Отель"),
                            ("cottage", "Гостевой дом / Баня"),
                        ],
                        default="hostel",
                        max_length=20,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="Хэш пароля"),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подтверждено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на регистрацию",
                "verbose_name_plural": "Заявки на регистрацию",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Если задано и дата прошла — организация в read-only режиме (нет активной подписки)",
                null=True,
                verbose_name="Триал до",
            ),
        ),
    ]
